server:
  port: 8090

api:
  jph:
    domain: "api.coingecko.com"
    endpoints:
      market: "/api/v3/coins/markets"
      list: "/api/v3/coins/list"
    path:
      apiKey: "CG-2iNrd82pQsgLnaaNbmB22VQc"

spring:
  data:
    redis:
      host: localhost
      port: 6379