server:
  port: 8090

api:
  jph:
    domain: "api.coingecko.com"
    endpoints:
      market: "/api/v3/coins/markets"
      list: "/api/v3/coins/list"
    path:
      apiKey: "CG-QaWUD2CVqQidGstHWcFgYg9e"
